---
# Tasks file for deploy
- name: "update and upgrade packages."
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
# (sudo apt autoremove)
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
# (sudo apt install nodejs npm)
- name: install deps
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
# Install pm2 (sudo npm install pm2 -g)
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
# (scp -i ~/.ssh/udacity_key.pem -r ./dist ubuntu@${IP_ADDRESS}:/home/ubuntu/app)
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
# Unzip artifact (tar -xzf artifact.tar.gz)
- name: start app
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start
